In [26]:
import pandas as pd
import numpy as np
data = pd.read_table('text.txt', sep = '\t')
data.set_index('Serial No.')
data

    Serial No.                                              Topic
0          1.0       Best hospital uniforms exporter company 1000
1          2.0                 Best dress manufacturer in BD 1000
2          3.0        Best skirt manufacturing company in BD 1000
3          4.0                       BD garments association 2000
4          5.0                  Posh garments: best clothing 1500
5          6.0          Posh garments: Lingerie manufacturer 1500
6          7.0  Top shipping agent in BD 1000 (this one was wr...
7          8.0                   Best crewing company in CTG 1000
8          9.0                     Top crewing agency in CTG 1000
9         10.0       ABM water company: best water treatment 1000
10        11.0              ABM water company: surface water 1000
11        12.0                 How long do RO membranes last 1000
12        13.0        Importance of effluent treatment plant 1000
13        14.0                      Iron removal plant in BD 1000
14        15.0                   Importance of surface water 1000
15        16.0             Safe electricity by walton cables 1000
16        17.0         Comfort sleep with walton ceiling fan 1000
17        18.0  Now everyday tornado with walton tornado fan 1000
18        19.0          Smooth conductivity by walton cables 1000
19        20.0                 Importance of circuit breaker 1000
20        21.0  How walton industrial solutions products help ...
21        22.0  Whats the benefit of walton double burner gas HOB
22        23.0       Benefit of walton glass top burner gas stove
23        24.0        Difference of infrared and induction cooker
24        25.0                       Top 50 double burner gas HOB
25        26.0                            Top 50 induction cooker

     Serial No.                                              Topic
NaN         1.0       Best hospital uniforms exporter company 1000
NaN         2.0                 Best dress manufacturer in BD 1000
NaN         3.0        Best skirt manufacturing company in BD 1000
NaN         4.0                       BD garments association 2000
NaN         5.0                  Posh garments: best clothing 1500
NaN         6.0          Posh garments: Lingerie manufacturer 1500
NaN         7.0  Top shipping agent in BD 1000 (this one was wr...
NaN         8.0                   Best crewing company in CTG 1000
NaN         9.0                     Top crewing agency in CTG 1000
NaN        10.0       ABM water company: best water treatment 1000
NaN        11.0              ABM water company: surface water 1000
NaN        12.0                 How long do RO membranes last 1000
NaN        13.0        Importance of effluent treatment plant 1000
NaN        14.0                      Iron removal plant in BD 1000
NaN        15.0                   Importance of surface water 1000
NaN        16.0             Safe electricity by walton cables 1000
NaN        17.0         Comfort sleep with walton ceiling fan 1000
NaN        18.0  Now everyday tornado with walton tornado fan 1000
NaN        19.0          Smooth conductivity by walton cables 1000
NaN        20.0                 Importance of circuit breaker 1000
NaN        21.0  How walton industrial solutions products help ...
NaN        22.0  Whats the benefit of walton double burner gas HOB
NaN        23.0       Benefit of walton glass top burner gas stove
NaN        24.0        Difference of infrared and induction cooker
NaN        25.0                       Top 50 double burner gas HOB
NaN        26.0                            Top 50 induction cooker